# Generated by Django 5.1.6 on 2025-03-13 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_ingresada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_ingresada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion_ingresada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulacion',
                'verbose_name_plural': 'Simulaciones',
                'db_table': 'simulaciones',
            },
        ),
        migrations.CreateModel(
            name='ValoresOptimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('global_admin', models.BooleanField(default=False)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Valores optimos',
                'verbose_name_plural': 'Valores optimos',
                'db_table': 'valores_optimos',
            },
        ),
    ]
