# Generated by Django 5.1.6 on 2025-03-01 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cultivos', '0005_alter_cultivo_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicionesAmbientales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_agua', models.DecimalField(decimal_places=1, max_digits=3)),
                ('fertilizante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultivos.fertilizantes')),
            ],
            options={
                'verbose_name': 'Condiciones Ambientales',
                'verbose_name_plural': 'Condiciones Ambientales',
                'db_table': 'condiciones_ambientales',
            },
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('resultado_esperado', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
                ('condiciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulaciones.condicionesambientales')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Simulacion',
                'verbose_name_plural': 'Simulaciones',
                'db_table': 'simulaciones',
            },
        ),
    ]
