# Generated by Django 5.1.6 on 2025-03-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoresoptimos',
            name='global_admin',
        ),
    ]
