# Generated by Django 5.1.6 on 2025-03-02 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0007_alter_cultivo_nombre'),
        ('simulaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecomendacionesCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('temperatura_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperatura_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitacion_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viento_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('viento_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ph_agua_min', models.DecimalField(decimal_places=1, max_digits=3)),
                ('ph_agua_max', models.DecimalField(decimal_places=1, max_digits=3)),
                ('cultivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Recomendacion de Cultivo',
                'verbose_name_plural': 'Recomendaciones de Cultivos',
                'db_table': 'recomendaciones_cultivo',
            },
        ),
    ]
