# Generated by Django 5.1.6 on 2025-03-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_remove_fertilizantes_cultivo_and_more'),
        ('simulaciones', '0002_remove_valoresoptimos_global_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoresoptimos',
            name='cultivo',
        ),
        migrations.AddField(
            model_name='simulacion',
            name='es_optimo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='valoresoptimos',
            name='tipo_cultivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.tipocultivo'),
            preserve_default=False,
        ),
    ]
