# Generated by Django 5.1.6 on 2025-03-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='vistas',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='votos_negativos',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='votos_positivos',
        ),
    ]
