# Generated by Django 5.1.6 on 2025-02-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_atualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tamaño')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': 'campos',
            },
        ),
    ]
