# Generated by Django 5.1.6 on 2025-03-01 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tamaño')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
                'db_table': 'campos',
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_suelo', models.IntegerField(choices=[(1, 'Arcilloso'), (2, 'Arenoso'), (3, 'Limoso'), (4, 'Franco'), (5, 'Pedregoso')])),
                ('temporada_ideal', models.IntegerField(choices=[(1, 'Primavera'), (2, 'Verano'), (3, 'Otoño'), (4, 'Invierno')])),
                ('requerimentos', models.TextField()),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'cultivos',
            },
        ),
        migrations.CreateModel(
            name='Fertilizantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia', models.IntegerField(choices=[(1, 'Diario'), (2, 'Semanal'), (3, 'Mensual'), (4, 'Trimestral'), (5, 'Anual')])),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Fertilizante',
                'verbose_name_plural': 'Fertilizantes',
                'db_table': 'fertilizante',
            },
        ),
        migrations.CreateModel(
            name='Pesticidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia', models.IntegerField(choices=[(1, 'Diario'), (2, 'Semanal'), (3, 'Mensual'), (4, 'Trimestral'), (5, 'Anual')])),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Pesticida',
                'verbose_name_plural': 'Pesticidas',
                'db_table': 'pesticida',
            },
        ),
        migrations.CreateModel(
            name='Plagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('efectos', models.TextField()),
                ('tratamiento', models.TextField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Plaga',
                'verbose_name_plural': 'Plagas',
                'db_table': 'plagas',
            },
        ),
    ]
