# Generated by Django 5.1.6 on 2025-03-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo'),
        ),
    ]
