# Generated by Django 5.1.6 on 2025-02-28 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campo',
            old_name='ultima_atualizacion',
            new_name='ultima_actualizacion',
        ),
    ]
