# Generated by Django 5.1.6 on 2025-03-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizantes',
            name='cultivo',
        ),
        migrations.RemoveField(
            model_name='pesticidas',
            name='cultivo',
        ),
        migrations.AddField(
            model_name='fertilizantes',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesticidas',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo'),
            preserve_default=False,
        ),
    ]
