# Generated by Django 5.1.6 on 2025-02-28 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0002_rename_ultima_atualizacion_campo_ultima_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_suelo', models.CharField(max_length=150)),
                ('temporada_ideal', models.CharField(max_length=150)),
                ('requerimentos', models.TextField()),
            ],
            options={
                'verbose_name': 'Cultivo',
                'verbose_name_plural': 'Cultivos',
                'db_table': 'cultivos',
            },
        ),
    ]
