# Generated by Django 5.1.6 on 2025-02-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0003_cultivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia', models.CharField(max_length=150)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Fertilizante',
                'verbose_name_plural': 'Fertilizantes',
                'db_table': 'fertilizante',
            },
        ),
        migrations.CreateModel(
            name='Pesticidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=20)),
                ('dosis', models.DecimalField(decimal_places=2, max_digits=5)),
                ('frecuencia', models.CharField(max_length=150)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Pesticida',
                'verbose_name_plural': 'Pesticidas',
                'db_table': 'pesticida',
            },
        ),
        migrations.CreateModel(
            name='Plagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre', models.CharField(max_length=150)),
                ('efectos', models.TextField()),
                ('tratamiento', models.TextField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Plaga',
                'verbose_name_plural': 'Plagas',
                'db_table': 'plagas',
            },
        ),
    ]
