# Generated by Django 5.1.6 on 2025-03-02 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0005_alter_cultivo_campo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificacionCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('fecha_plantacion', models.DateField()),
                ('fecha_cosecha', models.DateField()),
                ('cantidad_semillas', models.PositiveIntegerField()),
                ('rendimiento_esperado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'En proceso'), (3, 'Completada'), (4, 'Cancelada')], default=1)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.campo')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivos.cultivo')),
            ],
            options={
                'verbose_name': 'Planificacion de Cultivo',
                'verbose_name_plural': 'Planificaciones de Cultivos',
                'db_table': 'planificacion_cultivo',
            },
        ),
    ]
