# Generated by Django 5.1.6 on 2025-03-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0006_planificacioncultivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='nombre',
            field=models.IntegerField(choices=[(1, 'Papa'), (2, 'Arroz'), (3, 'Tomate'), (4, 'Trigo'), (5, 'Maíz')]),
        ),
    ]
