# Generated by Django 5.1.6 on 2025-03-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultivos', '0009_fertilizantes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizantes',
            name='user',
        ),
    ]
